# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yechan Lee (공사 중인 페이지 입니다.)
title: Mathematics Teacher
email: yclee@sasa.hs.kr
# blog: www.coslimites.com
# website: www.coslimites.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
### twitter_username: facespics
github_username: Yechan-Math
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: cos_limites
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0008-2184-9675

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://www.coslimites.com
  # - title: another link
  #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
  #   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_yclee.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Yechan Lee, and I am a teacher captivated by the beauty of mathematics. My dream is to inspire students by sharing my passion for this wonderful discipline. I am also a Ph.D. student in mathematics education.
  
  I am most skilled in: <mark>Math Geekery</mark> and <mark>Drinking Coffee</mark>

content:
  - title: Research Interest # Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title: Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sejong Academy of Science and Arts
        link: 
        sub_title: Mathematics Teacher
        caption: March 2017 - Present
        quote: >
          Currently teaching mathematics at Sejong Academy of Science and Arts since March 2017.
      - layout: text # Research Projects
        content: >
          **Research Projects:**
          - Participated in several research projects for developing selection tools for gifted education.
      - layout: text # Previous Experiences
        content: |
          **Previous Experiences:**
          - Osong High School, Mathematics Teacher, March 2013 - February 2017
          - Okchon Middle School, Mathematics Teacher, March 2011 - February 2013

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Korea National University of Education
        caption: March 2024 - Present
        sub_title: Ph.D. Mathematics Education
        quote: >
          Currently pursuing a Ph.D. in Mathematics Education at Korea National University of Education since March 2024.
      - layout: text # Previous Education
        content: >
          **Previous Education:**
          - MSc Mathematics Gifted Education, Korea National University of Education, February 2020
          - BSc Mathematics Education, Korea National University of Education, February 2011

  - title: Publications / Preprints
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      quote: >
        I have not published any papers yet.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in mathematics some of my other interests and hobbies are:
      - Happy TeXing # $\LaTeX$
      - Listening to Music

 # Look at this cool image  
 # ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
