# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

markdown: kramdown
mathjax: true

# Content configuration version
version: 2

# Personal info
name: Yechan Lee
title: Mathematics Teacher
email: yclee@sasa.hs.kr
# blog: www.coslimites.com
# website: www.coslimites.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
### twitter_username: facespics
# github_username: Yechan-Math
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# Additional icon links
additional_links:
  - title: My Blog link
    icon: fas fa-globe
    url: https://www.coslimites.com
  # - title: another link
  #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
  #   url: Link url (eg. https://google.com)


orcid_username: 0009-0008-2184-9675
instagram_username: cos_limites



# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_yclee.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Yechan Lee, and I am a teacher captivated by the beauty of mathematics. My dream is to inspire students by sharing my passion for this wonderful discipline. I recently returned to graduate school to study mathematics education.

  I did not go to university immediately after graduating from high school. Instead, I worked various part-time jobs and completed my military service. It was during this time that I decided, somewhat on a whim, to pursue higher education, and at the age of 26, I 'accidentally' found myself in the Department of Mathematics Education. While studying calculus at university, I was fortunate to experience the beauty of mathematics, and throughout my university years, I enjoyed and cherished every moment of studying math.

  I love my job as a 'math teacher' who shares mathematics with others. To better share my passion for math, I decided to pursue graduate studies, and I am continuing my studies in graduate school with the same joy and appreciation.
  
  I am most skilled in: <mark>Math Geekery</mark> and <mark>Drinking Coffee</mark>

content:
  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sejong Academy of Science and Arts
        link: 
        sub_title: Mathematics Teacher
        caption: March 2017 - Present 
        description: | # this will include new lines to allow paragraphs
          I have been working as a mathematics teacher at Sejong Academy of Science and Arts (SASA) since March 2017. SASA is the first school for gifted students in science and arts established in South Korea. I have enjoyed a rewarding time at SASA, interacting with diverse students and excellent colleagues. At SASA, I teach a variety of courses, including core mathematics subjects as well as additional subjects such as Calculus I,II(AP), Linear Algebra(AP), Discrete Mathematics, and Integrated Mathematics.
      - layout: left
        title: Other Projects
        sub_title: Various Dates
        description: | # this will include new lines to allow paragraphs
          I have participated in several research projects for developing assessment and selection tools for gifted education. I have also participated in projects translating books related to mathematics and mathematics education, and I have experience in developing textbooks. Additionally, I am currently involved in the Alice project.
      - layout: left
        title: Previous Experience
        sub_title: 
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>Osong High School, Mathematics Teacher, March 2013 - February 2017</li>
            <li>Okchon Middle School, Mathematics Teacher, March 2011 - February 2013</li>
          </ul>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Korea National University of Education
        caption: March 2024 - Present
        sub_title: Ph.D. student in Mathematics Education
        description: | # this will include new lines to allow paragraphs
          Currently pursuing a Ph.D. in Mathematics Education at Korea National University of Education since March 2024. I am fortunate to be able to continue working while pursuing my graduate studies, thanks to the support of my loving family, the understanding of my workplace, and the guidance of my graduate advisor.
      - layout: left
        title: Previous Education
        sub_title: 
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>M.S. in Mathematics Gifted Education, Korea National University of Education, February 2020 (Advisor: Yun Jong Gug)</li>
            <li>B.S. in Mathematics Education, Korea National University of Education, February 2011</li>
          </ul>

  - title: Publications / Preprints
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
        I have not published any papers yet.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in mathematics some of my other interests and hobbies are:
      - Happy TeXing
      - Listening to Music

 Look at this cool image  
 ![kyysdrawing](/images/kyysdrawing.jpg "kyysdrawing")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

mathjax:
  config: "TeX-MML-AM_CHTML"
